In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 

from scipy.stats import ttest_1samp
from scipy.stats import ttest_ind
from scipy.stats import binom
from statsmodels.formula.api import ols 
import statsmodels as sm

In [8]:
#Data upload 
df=pd.read_csv (r"C:\Users\sid\Downloads\Assignment_Statistics for Decision Making\property.csv")
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [9]:
print (df.head())

       Suburb           Address  Rooms Type      Price Method SellerG  \
0  Abbotsford      85 Turner St      2    h  1480000.0      S  Biggin
1  Abbotsford   25 Bloomburg St      2    h  1035000.0      S  Biggin
2  Abbotsford      5 Charles St      3    h  1465000.0     SP  Biggin
3  Abbotsford  40 Federation La      3    h   850000.0     PI  Biggin
4  Abbotsford       55a Park St      4    h  1600000.0     VB  Nelson

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN
1  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0
2  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0
3  4/03/2017       2.5    3067.0  ...       2.0  1.0      94.0           NaN
4  4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0         142.0

   YearBuilt  CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN        Yarra  -37.7996    144.9984  Northern Metropolitan
1     1900.0        Yarra  -37.8079    144.9934  Northern Metropolitan
2     1900.0        Yarra  -37.8093    144.9944  Northern Metropolitan
3        NaN        Yarra  -37.7969    144.9969  Northern Metropolitan
4     2014.0        Yarra  -37.8072    144.9941  Northern Metropolitan

  Propertycount
0        4019.0
1        4019.0
2        4019.0
3        4019.0
4        4019.0

[5 rows x 21 columns]

In [10]:
# Data cleaning 
print(df.shape)

(13580, 21)

In [11]:
print (df.isnull().sum())

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

In [12]:
#There are missing values in BuildingArea , YearBuilt and CouncilArea

In [13]:
#Removing rows where Price is missing
df=df.dropna(subset=['Price'])

In [14]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [18]:
print (df.shape)

(13580, 21)

In [22]:
# Convert Date Column into datetime format 
df['Date']= pd.to_datetime(df['Date'], dayfirst=True)

In [23]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,2016-12-03,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,2016-02-04,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,2017-03-04,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,2017-03-04,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,2016-06-04,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [24]:
#Extract year and month 
df['Year']= df['Date'].dt.year
df['Month']=df['Date'].dt.month

In [31]:
#Q1. Filter Altona Data 
altona = df[df['Suburb']== 'Altona']
print(altona['Price'].describe())

count    7.400000e+01
mean     8.348304e+05
std      2.915460e+05
min      3.910000e+05
25%      6.225000e+05
50%      7.735000e+05
75%      9.725000e+05
max      1.780000e+06
Name: Price, dtype: float64

In [36]:
#Hypotheses

#H0: Mean price = 800000

#H1: Mean price > 800000

In [41]:
stat, p_value = ttest_1samp(altona['Price'], popmean= 800000)

print('Test Statistic:', stat)
print('P-value:', p_value)

Test Statistic: 1.0277020770199676
P-value: 0.307483271305555

In [38]:
alpha = 0.05

if p_value/2 < alpha and stat > 0:
    print('Reject Null Hypothesis')
    print('Average property price has increased above $800,000')
else:
    print('Fail to Reject Null Hypothesis')

Fail to Reject Null Hypothesis

In [42]:
#the typical property price is $800,000

In [43]:
#Q2 summer vs winter property prices (2016)

In [44]:
sales_2016 = df[df['Year'] == 2016]

In [47]:
winter_months = [10, 11, 12, 1, 2, 3]
sales_2016['Season'] = sales_2016['Month'].apply(lambda x: 'Winter' if x in winter_months else 'Summer')

C:\Users\sid\AppData\Local\Temp\ipykernel_23636\3717410404.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_2016['Season'] = sales_2016['Month'].apply(lambda x: 'Winter' if x in winter_months else 'Summer')

In [51]:
winter_prices = sales_2016[sales_2016['Season'] == 'Winter']['Price']

summer_prices = sales_2016[sales_2016['Season'] == 'Summer']['Price']

In [52]:
#Hypotheses
#H0: No difference in average prices

#H1: There is a difference in average prices

In [53]:
stat, p_value = ttest_ind(winter_prices, summer_prices, equal_var=False)

print('Test Statistic:', stat)
print('P-value:', p_value)
if p_value < alpha:
    print('Reject Null Hypothesis')
    print('There is a significant difference between summer and winter prices')
else:
    print('Fail to Reject Null Hypothesis')

Test Statistic: 3.9211012778003753
P-value: 8.950129747463378e-05
Reject Null Hypothesis
There is a significant difference between summer and winter prices

In [54]:
# There is a significant differencce between summer and winter prices

In [55]:
#Q3 Probability of 3 Properties Without Car Parking in Abbotsford

In [56]:
abbotsford = df[df['Suburb'] == 'Abbotsford']

In [57]:
p = (abbotsford['Car'] == 0).mean()

print('Probability of no car parking:', round(p, 3))

Probability of no car parking: 0.268

In [58]:
probability = binom.pmf(3, 10, p)

print('Final Probability:', round(probability, 3))

Final Probability: 0.26

In [59]:
#Probability of finding is 26 %

In [60]:
#Q5 Probability of Finding a Property with 2 Bathrooms in Abbotsford

In [61]:
prob_2bath = (abbotsford['Bathroom'] == 2).mean()

print('Probability of 2-bathroom property:', round(prob_2bath, 3))

Probability of 2-bathroom property: 0.339

In [62]:
#Probability of finding is 33.9 %

In [63]:
#Q4 Probability of Finding a Property with 3 Rooms in Abbotsford

In [64]:
prob_3rooms = (abbotsford['Rooms'] == 3).mean()

print('Probability of 3-room property:', round(prob_3rooms, 3))

Probability of 3-room property: 0.357

In [65]:
# Probability is 35.7%

In [67]:
#Q6 Problem Statement

#A real estate firm claims that average property price in Richmond is $1,000,000.

In [68]:
richmond = df[df['Suburb'] == 'Richmond']

In [69]:
# Step 2: Hypotheses

#H0: Mean price = 1000000

#H1: Mean price ≠ 1000000

In [70]:
stat, p_value = ttest_1samp(richmond['Price'], popmean=1000000)

print('Test Statistic:', stat)
print('P-value:', p_value)

Test Statistic: 2.579547704074923
P-value: 0.01044499066415202

In [71]:
if p_value < alpha:
    print('Reject Null Hypothesis')
    print('Actual average price is significantly different from $1,000,000')
else:
    print('Fail to Reject Null Hypothesis')

Reject Null Hypothesis
Actual average price is significantly different from $1,000,000

In [72]:
# The real estate firm's claim soed not hold. The price is different from what what is informed. The actual price should be found.

In [74]:
#Q7 Problem Statement

#Do properties with car parking sell at higher prices?

In [75]:
with_car = df[df['Car'] > 0]['Price']

without_car = df[df['Car'] == 0]['Price']

In [76]:
#Hypothesis
#H0: Mean prices are equal

#H1: Properties with parking have higher prices

In [77]:
stat, p_value = ttest_ind(with_car, without_car, equal_var=False)

print('Test Statistic:', stat)
print('P-value:', p_value)

if p_value/2 < alpha and stat > 0:
    print('Reject Null Hypothesis')
    print('Properties with parking sell at higher prices')
else:
    print('Fail to Reject Null Hypothesis')

Test Statistic: -0.27224703025972535
P-value: 0.7854749985398599
Fail to Reject Null Hypothesis

In [78]:
# Properties with car parking do not sell at a higher price

In [79]:
#Q8 Problem Statement

#Check whether Price depends on:

#Suburb
#Type
#Interaction between Suburb and Type

In [82]:
# Import libraries

import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

# Select required columns

anova_df = df[['Suburb', 'Type', 'Price']].copy()

# Remove missing values

anova_df.dropna(inplace=True)

# Convert to categorical datatype

anova_df['Suburb'] = anova_df['Suburb'].astype('category')
anova_df['Type'] = anova_df['Type'].astype('category')

# OPTIONAL:
# Reduce suburbs if dataset is too large
# Keep only top 10 suburbs

top_suburbs = anova_df['Suburb'].value_counts().head(10).index

anova_df = anova_df[anova_df['Suburb'].isin(top_suburbs)]

# Fit Two-Way ANOVA model

model = ols(
    'Price ~ C(Suburb) + C(Type) + C(Suburb):C(Type)',
    data=anova_df
).fit()

# Generate ANOVA table

anova_table = sm.stats.anova_lm(model, typ=2)

# Display result

print(anova_table)

C:\Users\sid\anaconda3\Lib\site-packages\statsmodels\base\model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 313, but rank is 10
  warnings.warn('covariance of constraints does not have full '
C:\Users\sid\anaconda3\Lib\site-packages\statsmodels\base\model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 2, but rank is 0
  warnings.warn('covariance of constraints does not have full '
C:\Users\sid\anaconda3\Lib\site-packages\statsmodels\base\model.py:1923: RuntimeWarning: invalid value encountered in divide
  F /= J

                         sum_sq      df            F         PR(>F)
C(Suburb)          8.263888e+16   313.0  1715.819180   0.000000e+00
C(Type)                     NaN     2.0          NaN            NaN
C(Suburb):C(Type)  1.090166e+16   626.0   113.174844  1.482197e-323
Residual           3.534513e+14  2297.0          NaN            NaN

C:\Users\sid\anaconda3\Lib\site-packages\statsmodels\base\model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 626, but rank is 20
  warnings.warn('covariance of constraints does not have full '

In [83]:
#Final Business Insight
#Suburb significantly affects property prices.
#Interaction between Suburb and Type is also significant.
#Property Type alone could not be independently estimated because of data imbalance/multicollinearity.
#Different property types behave differently across different suburbs.

In [84]:
#Q9 p value interpretation 
p_vlaue= 0.032
alpha = 0.05 
if p_value < alpha:
    print('Reject Null Hypothesis')
else:
    print('Fail to Reject Null Hypothesis')

Fail to Reject Null Hypothesis

In [85]:
#Interpretation:
#A p-value of 0.032 means there is only a 3.2% chance that the observed difference occurred randomly.
#Since 0.032 < 0.05, we reject the null hypothesis.
#Business stakeholders can conclude that property prices between the two suburbs are significantly different.

In [86]:
#Q10 Problem Statement

#Do properties with more than 2 bathrooms command premium prices?

In [87]:
premium_bath = df[df['Bathroom'] > 2]['Price']

normal_bath = df[df['Bathroom'] <= 2]['Price']

In [88]:
# Hypothesis 
#H0: Mean prices are equal

#H1: Properties with more than 2 bathrooms have higher prices

In [90]:
stat, p_value = ttest_ind(premium_bath, normal_bath, equal_var=False)

print('Test Statistic:', stat)
print('P-value:', p_value)
if p_value/2 < alpha and stat > 0:
    print('Reject Null Hypothesis')
    print('Properties with more than 2 bathrooms command premium prices')
else:
    print('Fail to Reject Null Hypothesis')

Test Statistic: 28.800231483982945
P-value: 7.38042835669062e-137
Reject Null Hypothesis
Properties with more than 2 bathrooms command premium prices